### PR TITLE
Adding google analytics to the footer

### PR DESCRIPTION
**Pull request by andrewmil**
To enable the google analytics set environment variable `GOOGLE_ANALYTICS` to the correct code.

If no code is given the script will not be included

### CODE REVIEW

**Comment by dcdarrell9** [comment]
Is footer used everywhere? Would it be better to have the analytics in the _base template?

**Comment by andrewmil** [comment]
Base includes footer so there's no real difference I don't think

**Comment by rjweeks** [comment]
Can we do some checks with the developer tools to see if the javascript is delivered on different pages?

**Comment by andrewmil** [comment]
I had a quick look through all the pages I could get to and it was still there. We only have codes for pre-prod and prod so I think the idea is once it gets released we ask Chris Au if he's getting out info through

**Pull request merged**
