### PR TITLE
RAS-938 Upgrade Frontstage to Flask 3

### PR DESCRIPTION
**Pull request by arroyoAle**
# What and why?
Upgrading flask to version 3.0.0, the only changes that seem to affect frontstage are to the markup import which is used to display the success boxes when a message is successfully sent (and other things)

# How to test?
Deploy to your environment and run the acceptance tests, send a message from frontstage and check that the confirmation message is correctly flashed

# Jira
https://jira.ons.gov.uk/browse/RAS-938

### CODE REVIEW

**Review by LJBabbage — COMMENTED** [review]
Any idea why this was pinned in the first place? I know I did it in rm-reporting because it was using scaffold, seems odd that it was done if there were no changes needed

**Review by SteveScorfield — APPROVED** [review]
Tested and reviewed.

**Comment by arroyoAle** [comment]
> Any idea why this was pinned in the first place? I know I did it in rm-reporting because it was using scaffold, seems odd that it was done if there were no changes needed. Might be worth looking at blame in github and seeing if there is a comment on the PR

It was pinned in Steve's PR (https://github.com/ONSdigital/ras-frontstage/pull/939/files) but he had already updated the markup imports when it was pinned. Not sure exactly why it was pinned, seems to be test related issues that were solved by another fix and not unpinned

**Review by LJBabbage — APPROVED** [review]
Looks fine, you will inadvertently fix the crytography dependabot alert as well https://github.com/ONSdigital/ras-frontstage/security/dependabot/28

**Pull request merged**
