### PR TITLE
To do page iteration (2)

### PR DESCRIPTION
**Pull request by jeremygillies**
# What and why?
Feedback from business to To Do page.
Re-inserted "Period covered" to the todo screen

# How to test?
Check to see  Period covered label is shown before the period. 

# Trello
https://trello.com/c/QY8jiD6E/515-s32-user-self-serve-to-do-tab-page-design-alterations

### CODE REVIEW

**Review by creativeappdevamit — APPROVED** [review]

**Review by creativeappdevamit — CHANGES_REQUESTED** [review]
The UI doesn't look right

**Comment by jeremygillies** [comment]
I've committed a fix to the visual bug

**Review by creativeappdevamit — APPROVED** [review]

**Pull request merged**
