### PR TITLE
split tests into unit and integration, with separate make targets

### PR DESCRIPTION
**Pull request by jdfox**
# Motivation and Context
Separating unit tests from integration, to understand how long it may take for the other services

# What has changed
- Moved unit tests to tests/unit, and integration tests to tests/unit.
- Updated module imports in integration tests from tests.app to tests.integration
- Split targets in Makefile from "test" to "unit-tests" and "integration-tests"

# How to test?

On local build: 
```
make unit-tests
make integration-tests
```

# Links
https://trello.com/c/UoavPK4e

# Screenshots (if appropriate):

### CODE REVIEW

**Comment by jdfox** [comment]
Don't merge yet, just noticed README.md needs an update

**Comment by jterryons** [comment]
tests/unit/test_cookies_and_contact.py unit test fails for me. can you run that test without an environment?

**Comment by jdfox** [comment]
> tests/unit/test_cookies_and_contact.py test fails for me. can you run that test without an environment?

Locally this succeeds for me:
```
pipenv install --dev
make UNIT_TESTS=tests/unit/test_cookies_and_contact.py unit-tests
```

**Comment by jterryons** [comment]
im getting redis connection errors, its trying to connect to redis on localhost:6379. Looks like an integration test to me

**Comment by jdfox** [comment]
> im getting redis connection errors, its trying to connect to redis on localhost:6379. Looks like an integration test to me.

You're right, I missed that one, as there's no visible connection or mock in the code. And I had redis running locally. 

Moved test_cookies_and_contact.py from unit to integration, ran unit tests again (with redis stopped this time), and all passed, thanks.

**Pull request merged**
