### PR TITLE
Frontstage to use Pattern Library CDN

### PR DESCRIPTION
**Pull request by bennpearson**
# Motivation and Context
Using the Pattern Library CDN will help with the development workflow as all new components will pass through the Pattern Library where they go through IxD / Frontend review and accessibility testing.

# What has changed
* All JS comes from the Pattern Library CDN
* Most CSS comes from the Pattern Library CDN. 

# How to test?
Check CSS and JS is coming from the pattern library

# Links 
https://github.com/ONSdigital/sdc-global-design-patterns/pull/107
https://github.com/ONSdigital/sdc-global-design-patterns/pull/111

# ToDo once header and navigation are in the pattern library
In `_base.html`:
* Update `cdn_hash` version once the new header and navigation are in the Pattern Lib CDN
* Amend `cdn_url_prefix` to point to `https://cdn.ons.gov.uk/sdc/"~cdn_hash`
* Amend `scripts_cdn` to `bundle.min.js`

### CODE REVIEW

**Comment by bennpearson** [comment]
[Move Javascript libraries to ONS CDN](https://trello.com/c/aVGlWOIp/132-move-javascript-libraries-to-ons-cdn)

**Comment by emilioward** [comment]
Will need to run these changes past business/product owners @nicprice has said

**Comment by bennpearson** [comment]
@nicprice @emilioward Here is the new header: screen shot 2018-07-02 at 08 49 19

**Comment by jcox-dev** [comment]
Is this ready to merge or shall we hang fire with a "do not merge" label?

**Pull request merged**
